name: rpos_demo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.18.1

  cupertino_icons: ^1.0.6
  # State Management
  provider: ^6.0.5
    # Data
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0


flutter:
  uses-material-design: true
